dependencies:
  - name: kms-cmake-utils
    version: ">= 1.3.2"
  - name: kms-jsonrpc
    version: ">= 1.1.2"
  - name: gstreamer
    version: ">= 1.7.1"
  - name: gst-plugins-base
    version: ">= 1.7.1"
  - name: gst-plugins-good
    version: ">= 1.7.1"
  - name: gst-plugins-bad
    version: ">= 1.7.1"
  - name: gst-plugins-ugly
    version: ">= 1.7.1"
  - name: gst-libav
    version: ">= 1.7.1"
  - name: kurento-module-creator
    version: ">= 4.0.6"
